### ISSUE TITLE
Check the content of the readme file for 1.0.0

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKmod-Mechanical-Tool-Set#3]
Check the readme for completeness. E.g. more examples of use or content lists.

For the one tool I am still missing the name

![ASKmod-Mechanical-Tool-Set](https://user-images.githubusercontent.com/389294/104839762-8e0cc280-58c3-11eb-9c23-2bd42ac63c0d.jpg)

**Comment by timmwille** [comment]
adjustable wrench

**Comment by timmwille** [comment]
also there is a little mistake Content of the Black and Decker Roll

    Open-end wrench in the following sizes:
        19/17
        15/14
        13/12
        11/10
        9/8
    Ratchet with the following attachments:
        6 mm
        8 mm
        10 mm
        13 mm
        15 mm
        17 mm
        19 mm
    Ratchet screwdriver with the following attachments:
        Cross screwdriver in 14 different sizes
        Slotted screwdriver in 8 different sizes
        Torx attachments in 6 different sizes
    Pliers
    Needle nose pliers
    Flashlight
    Spare batteries
    Allen wrench
    Pointing stick
    Adjustable wrench

Content added

    Metal garden wire with 0.5 mm diameter and 40 m length
